# Generated by Django 3.2.5 on 2021-07-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anylease', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
